# Generated by Django 5.2.15 on 2026-06-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'athletic_test_types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='AthleticTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletic_test_results', to='people.playerteam')),
                ('athletic_test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluations.athletictesttype')),
            ],
            options={
                'db_table': 'athletic_test_results',
                'ordering': ['-test_date', 'player_team'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='people.playerteam')),
            ],
            options={
                'db_table': 'player_measurements',
                'ordering': ['-measurement_date', 'player_team'],
            },
        ),
    ]
