# Generated by Django 5.2.15 on 2026-06-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationcategory_evaluationcriteria'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('evaluated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='people.playerteam')),
            ],
            options={
                'db_table': 'player_evaluations',
                'ordering': ['-evaluation_date', 'player_team'],
            },
        ),
        migrations.CreateModel(
            name='PlayerEvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='evaluations.evaluationcriteria')),
                ('player_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.playerevaluation')),
            ],
            options={
                'db_table': 'player_evaluation_items',
                'ordering': ['player_evaluation', 'evaluation_criteria'],
            },
        ),
        migrations.CreateModel(
            name='PlayerLevelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('level', models.PositiveSmallIntegerField()),
                ('evaluated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_evaluations', to='people.playerteam')),
            ],
            options={
                'db_table': 'player_level_evaluations',
                'ordering': ['-evaluation_date', 'player_team'],
            },
        ),
    ]
