# Generated by Django 5.2.15 on 2026-06-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('player_team', 'training_session'), name='uq_player_training_session_attendance'),
        ),
        migrations.AddConstraint(
            model_name='staffattendancerecord',
            constraint=models.UniqueConstraint(fields=('team_coach', 'training_session'), name='uq_staff_training_session_attendance'),
        ),
    ]
